### ISSUE TITLE
Django request body can include sensitive data

### ISSUE THREAD

**Issue by sabw8217** [rollbar/pyrollbar#175] opened 2017-06-23 19:22 UTC
Post requests can include sensitive data in the request body. Sensitive POST params can be scrubbed from the request.POST attributes but not from the request body itself.

I think this works for other frameworks (werkzeug, bottle) because the body is only included if it's JSON and can then be scrubbed, but the django body is just a string.

**Comment by sabw8217** [comment] 2017-06-23 19:23
Simplest possible fix is here: 
https://github.com/rollbar/pyrollbar/pull/174

**Comment by ezarowny** [comment] 2017-06-26 22:34
Hey @sabw8217, thanks for contributing! I've thought about this before and something like your approach is probably a good idea. I'll take a further look soon.

**Comment by sabw8217** [comment] 2017-06-27 00:44
I tried to figure out if there was something cleverer to do here than just remove the body, but almost anything reasonable is going to be in `dict(request.POST)` anyhow.

**Comment by ezarowny** [comment] 2017-07-03 17:07
I've merged #174 and I'll make a release soon. We can always add request.body back later if someone really needs it by decoding the byte string and loading it as JSON. We'd be able to scrub the body then.

**Comment by sabw8217** [comment] 2017-07-12 18:45
Thanks @ezarowny !

**Comment by remarkov** [comment] 2018-12-06 19:21
Dear @ezarowny 
We heavily use pyrollbar in our project and by design a lot of data that helps us in debugging can often be found in request.body. For some time we were using an old version of pyrollbar and did not notice this change but recently we've updated to the latest version and miss the request.body info badly. Is there any chance this can be brought back, maybe optional? Thanks!

**Comment by rokob** [comment] 2018-12-06 20:17
We could do one of two things:

1) Add it back exactly how it worked before, but behind a configuration option which defaults to off. This would allow you to be able to turn on the feature and accept that it would not be scrubbed.
2) Attempt to decode the body into JSON and therefore be able to scrub it.

The first option is easier, but the second is probably more inline with the rest of the library.

**Comment by remarkov** [comment] 2018-12-07 07:09
Well, I would be happy with any of these options as they will both work fine for our case. However I agree the second option would look more consistent. Since the first one is easy to implement it may have sense to do that for now and extend it with scrubbing on a later stage?I guess these options are not mutually exclusive. In any way, thanks for stepping in!

**Comment by remarkov** [comment] 2019-02-07 16:03
Hi @rokob 
Did you have a chance to look at the issue?

**Closed** 2019-02-27 01:08 UTC
